// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzgvcejjjrmfyeludeul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6Z3ZjZWpqanJtZnllbHVkZXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5OTAwODAsImV4cCI6MjA2ODU2NjA4MH0.87yQ_QKRIoUskkJkr1F3NGwotgflprI5lzTnR-JWdk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});